### ISSUE TITLE
使用純 CSS 建構表單的選項 UI

### ISSUE THREAD

**Issue by VisionYi** [VisionYi/blog#1]
> created date - Mar 3, 2019

在製作網頁上表單是很常見需求，而當中的選項功能不外乎就是 `checkbox`、`radio`、`switch`，點擊變化的行為是可以用單純的原生 CSS 刻出來的，由於要適用於表單上，所以 label 標籤的呈現也是重要的。

基本上會前端的工程師都知道使用 input `id` 搭配 label `for` 就能呈現勾選或開關的動態效果，以下為最簡單的例子：

```html
<!-- html -->
<input type="checkbox" id="id-1">
<label for="id-2"></label>
```

```css
/* css */
input[type="checkbox"] {
  display: none;
}

input[type="checkbox"]:checked + label {
  background-color: #aaa;
}

label {
  display: inline-block;
  width: 15px;
  height: 15px;
  border: 1px solid #000;
  cursor: pointer;
}
```

接下進入我們的主題，先以 `checkbox` 為例：
- 第一點
  - 我們要呈現勾選的 UI ，最快最美的方式就是使用圖片或 icon ，但這種方式是浪費資源 (X)
  - 用原生的 CSS 即可刻出來，我們使用偽元素 `before` & `after`，還能結合 CSS 動畫效果
- 第二點
  - 為了用於表單能使用方便，我們把 UI 與 文字部分分開，此組件內部細分 `controls` 代表 UI & `label` 代表文字
  - `controls` 放入 input & 偽元素組成的 UI
  - `label` 就能自由放入文字或連結元素
- 第三點
  - 其實原生瀏覽器的 input UI 只要看不見但可以點擊到，有動作就行了，我們使用 CSS `opacity: 0;`
- 第四點
  - 藉由 input CSS 偽類 `:checked`、`:focus`、`:invalid`，可以指定我們的 UI 介面自動做出變化

以下為程式碼的部分：

```html
<div class="checkbox">
  <div class="checkbox__controls">
    <input type="checkbox" id="id-2">
    <i class="checkbox__icon"></i>
  </div>
  <label for="id-2" class="checkbox__label">
    checkbox
    <a href="#">link</a>
  </label>
</div>
```

```scss
// scss
.checkbox {
  &__controls {
    display: inline-block;
    vertical-align: middle;
    position: relative;
    width: 18px;
    height: 18px;
    transition: all .2s;
  }
  
  &__icon {
    display: block;
    position: relative;
    width: 100%;
    height: 100%;
    border: 1px solid #bcbcbc;
    border-radius: 2px;
    transition: inherit;
  }
  
  input[type="checkbox"] {
    display: block;
    position: absolute;
    width: 100%;
    height: 100%;
    margin: 0;
    opacity: 0;
    z-index: 1;
    cursor: pointer;
    
    &:focus + .checkbox__icon {
      border: 1px solid #888;
    }
    
    &:checked + .checkbox__icon {
      background-color: #18D;
      border-color: #18D;
      
      &::before {
        content: '';
        display: block;
        position: absolute;
        background-color: #fff;
        left: 1px;
        top: 10.5px;
        width: 6.5px;
        height: 3px;
        transform: rotate(45deg);
        transform-origin: right center;
      }

      &::after {
        content: '';
        display: block;
        position: absolute;
        background-color: #fff;
        left: 6.5px;
        top: 11px;
        width: 12px;
        height: 3px;
        transform: rotate(-52deg);
        transform-origin: left center; 
      }
    }
  }
  
  &__label {
    display: inline;
    vertical-align: middle;
    cursor: pointer;
  }
}
```

另外表單選項還有 `radio` 與 `switch` 也是類似的概念去建構的。
以下是三種 form option `checkbox`、`radio`、`switch` 所呈現的效果：
